// Authentication
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';

export const CHANGE_PASSWORD_SET_SUCCESS = 'CHANGE_PASSWORD_SET_SUCCESS'
export const CHANGE_PASSWORD_SET_FAIL = 'CHANGE_PASSWORD_SET_FAIL'

// Account Activation
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
//Cargador
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';
// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// Logout
export const LOGOUT = 'LOGOUT';
// Reset Password
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';



// User Profile ****************************************** Obtener el perfil y actualizarlo
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';

export const GET_USER_LOCATION_SUCCESS = 'GET_USER_LOCATION_SUCCESS';
export const GET_USER_LOCATION_FAIL = 'GET_USER_LOCATION_FAIL';
export const UPDATE_USER_LOCATION_SUCCESS = 'UPDATE_USER_LOCATION_SUCCESS';
export const UPDATE_USER_LOCATION_FAIL = 'UPDATE_USER_LOCATION_FAIL';


// Store Categories  *************************************************
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const SET_CATEGORY_LOADING = 'SET_CATEGORY_LOADING';
export const REMOVE_CATEGORY_LOADING = 'REMOVE_CATEGORY_LOADING';

// Stores ******************************************************
export const GET_STORES_SUCCESS = 'GET_STORES_SUCCESS';
export const GET_STORES_FAIL = 'GET_STORES_FAIL';

export const GET_STORE_LIST_CATEGORIES_SUCCESS = 'GET_STORE_LIST_CATEGORIES_SUCCESS';
export const GET_STORE_LIST_CATEGORIES_FAIL = 'GET_STORE_LIST_CATEGORIES_FAIL';

export const GET_STORE_SUCCESS = 'GET_STORE_SUCCESS';
export const GET_STORE_FAIL = 'GET_STORE_FAIL';

export const RELATED_STORES_SUCCESS = 'RELATED_STORES_SUCCESS';
export const RELATED_STORES_FAIL = 'RELATED_STORES_FAIL';

export const SEARCH_STORES_SUCCESS = 'SEARCH_STORES_SUCCESS';
export const SEARCH_STORES_FAIL = 'SEARCH_STORES_FAIL';

export const GET_STORES_BY_ARRIVAL_SUCCESS = 'GET_STORES_BY_ARRIVAL_SUCCESS';
export const GET_STORES_BY_ARRIVAL_FAIL = 'GET_STORES_BY_ARRIVAL_FAIL';

export const SET_STORE_LOADING = 'SET_STORE_LOADING';
export const REMOVE_STORE_LOADING = 'REMOVE_STORE_LOADING';

export const GET_STORE_POLICIES_SUCCESS = 'GET_STORE_POLICIES_SUCCESS';
export const GET_STORE_POLICIES_FAIL = 'GET_STORE_POLICIES_FAIL';


export const SET_STORES_LOADING = 'SET_STORES_LOADING';
export const REMOVE_STORES_LOADING = 'REMOVE_STORES_LOADING';

export const GET_STORE_LIKES_DISLIKE_SUCCESS = 'GET_STORE_LIKES_DISLIKE_SUCCESS';
export const GET_STORE_LIKES_DISLIKE_FAIL = 'GET_STORE_LIKES_DISLIKE_FAIL';


export const SET_LOADING_STORE_LIKES_DISLIKE = 'SET_LOADING_STORE_LIKES_DISLIKE';
export const REMOVE_LOADING_STORE_LIKES_DISLIKE = 'REMOVE_LOADING_STORE_LIKES_DISLIKE';

export const ADD_STORE_LIKES_DISLIKE_SUCCESS = 'ADD_STORE_LIKES_DISLIKE_SUCCESS';
export const ADD_STORE_LIKES_DISLIKE_FAIL = 'ADD_STORE_LIKES_DISLIKE_FAIL';



//**************************** */
export const SET_STORE_LOADING_FAIL = 'SET_STORE_LOADING';
//**************************** */

export const GET_STORES_BY_SOLD_SUCCESS = 'GET_STORES_BY_SOLD_SUCCESS';
export const GET_STORES_BY_SOLD_FAIL = 'GET_STORES_BY_SOLD_FAIL';

export const FILTER_STORES_SUCCESS = 'FILTER_STORES_SUCCESS';
export const FILTER_STORES_FAIL = 'FILTER_STORES_FAIL';

// products categories ******************************************************
export const GET_PRODUCTS_LIST_CATEGORIES_STORE_SUCCESS = 'GET_PRODUCTS_LIST_CATEGORIES_STORE_SUCCESS';
export const GET_PRODUCTS_LIST_CATEGORIES_STORE_FAIL = 'GET_PRODUCTS_LIST_CATEGORIES_STORE_FAIL';

export const SET_CATEGORY_PRODUCT_LOADING = 'SET_CATEGORY_PRODUCT_LOADING';
export const REMOVE_CATEGORY_PRODUCT_LOADING = 'REMOVE_CATEGORY_PRODUCT_LOADING';

// products ******************************************************
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_OPTIONS_SUCCESS = 'GET_OPTIONS_SUCCESS';
export const GET_OPTIONS_FAIL = 'GET_OPTIONS_FAIL';

export const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING';
export const REMOVE_PRODUCTS_LOADING = 'REMOVE_PRODUCTS_LOADING';

export const GET_PRODUCTS_LIST_BY_CATEGORIES_STORE_SUCCESS = 'GET_PRODUCTS_LIST_BY_CATEGORIES_STORE_SUCCESS';
export const GET_PRODUCTS_LIST_BY_CATEGORIES_STORE_FAIL = 'GET_PRODUCTS_LIST_BY_CATEGORIES_STORE_FAIL';

export const SET_PRODUCTS_LIST_BY_CATEGORIES_STORE_LOADING = 'SET_PRODUCTS_LIST_BY_CATEGORIES_STORE_LOADING';
export const REMOVE_PRODUCTS_LIST_BY_CATEGORIES_STORE_LOADING = 'REMOVE_PRODUCTS_LIST_BY_CATEGORIES_STORE_LOADING';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';

export const SET_PRODUCT_LOADING = 'SET_PRODUCT_LOADING';
export const REMOVE_PRODUCT_LOADING = 'REMOVE_PRODUCT_LOADING';

export const GET_PRODUCT_LIKES_DISLIKE_SUCCESS = 'GET_PRODUCT_LIKES_DISLIKE_SUCCESS';
export const GET_PRODUCT_LIKES_DISLIKE_FAIL = 'GET_PRODUCT_LIKES_DISLIKE_FAIL';


export const SET_LOADING_PRODUCT_LIKES_DISLIKE = 'SET_LOADING_PRODUCT_LIKES_DISLIKE';
export const REMOVE_LOADING_PRODUCT_LIKES_DISLIKE = 'REMOVE_LOADING_PRODUCT_LIKES_DISLIKE';

export const ADD_PRODUCT_LIKES_DISLIKE_SUCCESS = 'ADD_PRODUCT_LIKES_DISLIKE_SUCCESS';
export const ADD_PRODUCT_LIKES_DISLIKE_FAIL = 'ADD_PRODUCT_LIKES_DISLIKE_FAIL';

export const GET_FILTERED_PRODUCTS_SUCCESS = 'GET_FILTERED_PRODUCTS_SUCCESS';
export const GET_FILTERED_PRODUCTS_FAIL = 'GET_FILTERED_PRODUCTS_FAIL';

export const GET_FILTERED_PRODUCTS_BY_CATEGORIES_SUCCESS = 'GET_FILTERED_PRODUCTS_BY_CATEGORIES_SUCCESS';
export const GET_FILTERED_BY_CATEGORIES_PRODUCTS_FAIL = 'GET_FILTERED_BY_CATEGORIES_PRODUCTS_FAIL';


// Cart (base de datos)
export const USER_CARTS_SUCCESS = 'USER_CARTS_SUCCESS';
export const USER_CARTS_FAIL = 'USER_CARTS_FAIL';

export const SET_CARTS_LOADED = 'SET_CARTS_LOADED';
export const REMOVE_CARTS_LOADED = 'REMOVE_CARTS_LOADED';

export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';

export const SET_ADD_ITEM_LOADED = 'ADD_ITEM_LOADED_SUCCESS';
export const REMOVE_ADD_ITEM_LOADED = 'ADD_ITEM_LOADED_FAIL';

export const USER_CART_SUCCESS = 'USER_CART_SUCCESS';
export const USER_CART_FAIL = 'USER_CART_FAIL';

export const INCREMENT_ITEM_SUCCESS = 'INCREMENT_ITEM_SUCCESS';
export const INCREMENT_ITEM_FAIL = 'INCREMENT_ITEM_FAIL';

export const DECREMENT_ITEM_SUCCESS = 'DECREMENT_ITEM_SUCCESS';
export const DECREMENT_ITEM_FAIL = 'DECREMENT_ITEM_FAIL';

export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL';

export const REMOVE_CART_SUCCESS = 'REMOVE_CART_SUCCESS';
export const REMOVE_CART_FAIL = 'REMOVE_CART_FAIL';

export const SYNCH_CART_SUCCESS = 'SYNCH_CART_SUCCESS';
export const SYNCH_CART_FAIL = 'SYNCH_CART_FAIL';

// Shipping
export const GET_SHIPPING_OPTION_SUCCESS = 'GET_SHIPPING_OPTION_SUCCESS';
export const GET_SHIPPING_OPTION_FAIL = 'GET_SHIPPING_OPTION_FAIL';

// cities
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_FAIL = 'GET_CITIES_FAIL';




// Comentatios tiendas ******************************************************* 

export const GET_COMMENT_STORE_SUCCESS = 'GET_COMMENT_STORE_SUCCESS';
export const GET_COMMENT_STORE_FAIL = 'GET_COMMENT_STORE_FAIL';

export const ADD_COMMENT_STORE_SUCCESS = 'ADD_COMMENT_STORE_SUCCESS';
export const ADD_COMMENT_STORE_FAIL = 'ADD_COMMENT_STORE_FAIL';

export const DELETE_COMMENT_STORE_SUCCESS = 'DELETE_COMMENT_STORE_SUCCESS';
export const DELETE_COMMENT_STORE_FAIL = 'DELETE_COMMENT_STORE_FAIL';

export const EDIT_COMMENT_STORE_SUCCESS = 'EDIT_COMMENT_STORE_SUCCESS';
export const EDIT_COMMENT_STORE_FAIL = 'EDIT_COMMENT_STORE_FAIL';


// Compra ******************************************************* 

export const INVOICE_SUCCESS = 'INVOICE_SUCCESS';
export const INVOICE_FAIL = 'INVOICE_FAIL';

export const SET_LOADER_INVOICE = 'SET_LOADER_INVOICE';
export const REMOVE_LOADER_INVOICE = 'REMOVE_LOADER_INVOICE';

export const INVOICES_SUCCESS = 'INVOICES_SUCCESS';
export const INVOICES_FAIL = 'INVOICES_FAIL';

export const INVOICES_SUCCESS_DELETE = 'INVOICES_SUCCESS_DELETE';
export const INVOICES_FAIL_DELETE = 'INVOICES_FAIL_DELETE';



// Comentatios products ******************************************************* 

export const GET_COMMENT_PRODUCT_SUCCESS = 'GET_COMMENT_PRODUCT_SUCCESS';
export const GET_COMMENT_PRODUCT_FAIL = 'GET_COMMENT_PRODUCT_FAIL';

export const ADD_COMMENT_PRODUCT_SUCCESS = 'ADD_COMMENT_PRODUCT_SUCCESS';
export const ADD_COMMENT_PRODUCT_FAIL = 'ADD_COMMENT_PRODUCT_FAIL';

export const DELETE_COMMENT_PRODUCT_SUCCESS = 'DELETE_COMMENT_PRODUCT_SUCCESS';
export const DELETE_COMMENT_PRODUCT_FAIL = 'DELETE_COMMENT_PRODUCT_FAIL';

export const EDIT_COMMENT_PRODUCT_SUCCESS = 'EDIT_COMMENT_PRODUCT_SUCCESS';
export const EDIT_COMMENT_PRODUCT_FAIL = 'EDIT_COMMENT_PRODUCT_FAIL';

// Productos Liked *********************************************************
export const GET_PRDUCTS_LIKED_SUCCESS = 'GET_PRDUCTS_LIKED_SUCCESS';
export const GET_PRDUCTS_LIKED_FAIL = 'GET_PRDUCTS_LIKED_FAIL';

// Stores Liked *********************************************************
export const GET_STORES_LIKED_SUCCESS = 'GET_STORES_LIKED_SUCCESS';
export const GET_STORES_LIKED_FAIL = 'GET_STORES_LIKED_FAIL';



