# Generated by Django 5.0 on 2024-02-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_category', '0002_category_slug_category_views_viewcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
