# Generated by Django 4.2.10 on 2024-05-29 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_category', '0003_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='views',
        ),
    ]
