# Generated by Django 5.0 on 2024-01-18 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_currency_options'),
        ('locations', '0002_alter_ciudad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.currency'),
        ),
    ]
