# Generated by Django 4.2.10 on 2024-06-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_pais_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='countrycode',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
