# Generated by Django 5.0 on 2024-02-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_products_invoice_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
