# Generated by Django 5.0 on 2024-02-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
