# Generated by Django 5.0 on 2024-02-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_pdf_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
