# Generated by Django 5.0 on 2024-02-22 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_invoice_cart'),
        ('shipping', '0005_alter_shipping_name'),
        ('store', '0017_store_address'),
        ('user_profile', '0009_userprofile_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.userlocation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.shipping'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoicestatus'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store'),
        ),
    ]
