# Generated by Django 4.2.10 on 2024-04-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_invoice_buyer_alter_invoice_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.CharField(max_length=20),
        ),
    ]
