# Generated by Django 4.2.10 on 2024-05-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_alter_invoice_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_path',
        ),
    ]
