# Generated by Django 4.2.10 on 2024-05-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_remove_invoice_pdf_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transaction_number',
            field=models.CharField(blank=True, default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
