# Generated by Django 4.2.10 on 2024-05-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_remove_invoice_pdf_path_alter_invoice_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
