# Generated by Django 4.2.10 on 2024-05-31 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_faq_answer'),
        ('invoice', '0018_alter_invoice_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoicestatus')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'unique_together': {('store', 'status')},
            },
        ),
    ]
