# Generated by Django 4.2.10 on 2024-05-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_alter_invoice_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreStatus',
        ),
    ]
