# Generated by Django 5.0 on 2024-01-23 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
        ('store', '0014_remove_store_category_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_store', to='store.store'),
            preserve_default=False,
        ),
    ]
