# Generated by Django 5.0 on 2024-01-23 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shipping_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='additional_notes',
        ),
        migrations.AlterField(
            model_name='shipping',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
