# Generated by Django 5.0 on 2024-01-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_remove_shipping_additional_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='additional_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
