# Generated by Django 5.0 on 2024-01-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_shipping_additional_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
