# Generated by Django 4.2.10 on 2024-04-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_alter_shipping_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
