# Generated by Django 4.2.10 on 2024-04-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0010_alter_shipping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
