# Generated by Django 4.2.10 on 2024-05-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0012_alter_shipping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='additional_notes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
