# Generated by Django 5.0 on 2024-02-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='total_items',
        ),
    ]
