# Generated by Django 5.0 on 2024-02-02 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_option_value'),
        ('wishlist', '0002_remove_wishlist_total_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='store',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WishListItem',
        ),
    ]
