# Generated by Django 5.0 on 2024-02-05 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_likes'),
        ('wishlist', '0005_remove_wishlist_product_wishlist_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='store',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
    ]
