// stores
export const USERS_STORE_SUCCESS = 'USERS_STORE_SUCCESS';
export const USERS_STORE_FAIL = 'USERS_STORE_FAIL';


// loading
export const SET_LOADING_STORE_USERS = 'SET_LOADING_STORE_USERS';
export const REMOVE_LOADING_STORE_USERS = 'REMOVE_LOREMOVE_LOADING_STORE_USERSADED_STORE';
