# Generated by Django 5.0 on 2024-01-26 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
