# Generated by Django 5.0 on 2024-01-27 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('sabor', 'Sabor'), ('color', 'Color')], max_length=100)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'opción',
                'verbose_name_plural': 'opciones',
            },
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='option_type',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='value',
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='product.product'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.option'),
            preserve_default=False,
        ),
    ]
