# Generated by Django 5.0 on 2024-01-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_option_remove_productoption_option_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
