# Generated by Django 5.0 on 2024-01-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productoption_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity_available',
            field=models.IntegerField(default=0, verbose_name='Cantidad total disponible'),
        ),
    ]
