# Generated by Django 5.0 on 2024-01-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_rename_total_quantity_available_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='option',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
    ]
