# Generated by Django 5.0 on 2024-01-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
