# Generated by Django 5.0 on 2024-01-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productoption_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
