# Generated by Django 5.0 on 2024-01-29 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_productoption_sold'),
        ('store', '0015_alter_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='store',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='options_store', to='store.store'),
            preserve_default=False,
        ),
    ]
