# Generated by Django 5.0 on 2024-01-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_option_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
