# Generated by Django 4.2.10 on 2024-03-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_product_views_delete_viewcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
