# Generated by Django 4.2.10 on 2024-04-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_product_price_alter_product_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Impuesto del producto', max_digits=10),
        ),
    ]
