# Generated by Django 4.2.10 on 2024-04-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_product_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
