# Generated by Django 4.2.10 on 2024-04-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_remove_product_tax_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
    ]
