# Generated by Django 4.2.10 on 2024-05-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_productoption_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
