# Generated by Django 4.2.10 on 2024-05-14 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_pais_currency'),
        ('product', '0038_remove_product_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.pais'),
            preserve_default=False,
        ),
    ]
