# Generated by Django 4.2.10 on 2024-05-14 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_product_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pais',
        ),
    ]
