# Generated by Django 4.2.10 on 2024-05-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_alter_product_price_alter_product_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
    ]
