# Generated by Django 4.2.10 on 2024-05-15 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_alter_product_price_alter_product_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
