# Generated by Django 4.2.10 on 2024-05-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_alter_product_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
