# Generated by Django 4.2.10 on 2024-05-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_remove_product_is_stock_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='is_stock_low',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productoption',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
