# Generated by Django 4.2.10 on 2024-05-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_productoption_is_stock_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_low_stock_alert',
            field=models.BooleanField(default=False),
        ),
    ]
