# Generated by Django 4.2.10 on 2024-06-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_product_is_low_stock_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento en porcentaje', max_digits=5),
        ),
    ]
