# Generated by Django 5.0 on 2024-01-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='store',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
