# Generated by Django 5.0 on 2024-01-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='carts', to='cart.itemcarrito'),
        ),
    ]
