# Generated by Django 5.0 on 2024-01-13 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cart_products_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=2, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart'),
        ),
    ]
