# Generated by Django 5.0 on 2024-01-13 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_items_itemcarrito_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='subtotal',
        ),
    ]
