# Generated by Django 5.0 on 2024-01-28 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_itemcarrito_option'),
        ('product', '0017_productoption_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.option'),
        ),
    ]
