# Generated by Django 5.0 on 2024-01-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_itemcarrito_option'),
        ('product', '0020_alter_option_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='option',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='product',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='product_option',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='product.productoption'),
            preserve_default=False,
        ),
    ]
