# Generated by Django 5.0 on 2024-01-25 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_pais_currency'),
        ('user_profile', '0002_remove_userprofile_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('postal_zip_code', models.CharField(max_length=20)),
                ('telephone_number', models.CharField(max_length=255)),
                ('delivery_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations.ciudad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
    ]
