# Generated by Django 5.0 on 2024-02-01 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_pais_currency'),
        ('user_profile', '0007_remove_userlocation_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.ciudad'),
        ),
    ]
