# Generated by Django 4.2.10 on 2024-03-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0003_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
