// Shippings  *************************************************

export const GET_SHIPPINGS_SUCCESS = 'GET_SHIPPINGS_SUCCESS';
export const GET_SHIPPINGS_FAIL = 'GET_SHIPPINGS_FAIL';

export const SET_SHIPPINGS_LOADING = 'SET_SHIPPINGS_LOADING';
export const REMOVE_SHIPPINGS_LOADING = 'REMOVE_SHIPPINGS_LOADING';

export const ADD_SHIPPINGS_SUCCESS = 'ADD_SHIPPINGS_SUCCESS';
export const ADD_SHIPPINGS_FAIL = 'ADD_SHIPPINGS_FAIL';

export const DELETE_SHIPPING_SUCCESS = 'DELETE_SHIPPING_SUCCESS';
export const DELETE_SHIPPING_FAIL = 'DELETE_SHIPPING_FAIL';