# Generated by Django 5.0 on 2023-12-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='store',
            name='likes',
        ),
        migrations.AddField(
            model_name='store',
            name='dislikes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='likes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
