# Generated by Django 5.0 on 2023-12-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_store_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
