# Generated by Django 5.0 on 2024-01-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_store_dislikes_remove_store_likes_and_more'),
        ('store_category', '0002_category_slug_category_views_viewcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ManyToManyField(to='store_category.category'),
        ),
    ]
