# Generated by Django 5.0 on 2024-01-27 18:44

import apps.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_store_category_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(default='store/store_profile.png', upload_to=apps.store.models.store_directory_path_profile),
        ),
    ]
