# Generated by Django 5.0 on 2024-02-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_store_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='dislikes',
            new_name='complaints',
        ),
    ]
