# Generated by Django 5.0 on 2024-02-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_dislikes_store_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
