# Generated by Django 5.0 on 2024-02-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_store_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='nit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
