# Generated by Django 4.2.10 on 2024-04-19 03:38

import apps.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_store_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=apps.store.models.store_directory_qr),
        ),
    ]
