# Generated by Django 4.2.10 on 2024-04-21 02:17

import apps.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_store_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='banner',
            field=models.ImageField(upload_to=apps.store.models.store_directory_path_banner),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(upload_to=apps.store.models.store_directory_path_profile),
        ),
    ]
