# Generated by Django 4.2.10 on 2024-05-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_store_banner_alter_store_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
