# Generated by Django 4.2.10 on 2024-05-02 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_store_location_storepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepolicy',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storepolicy',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='store.store'),
        ),
    ]
