# Generated by Django 4.2.10 on 2024-05-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_storepolicy_name_alter_storepolicy_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepolicy',
            name='policy_text',
            field=models.TextField(max_length=1000),
        ),
    ]
