# Generated by Django 4.2.10 on 2024-05-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_storepolicy_policy_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='x_red_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
