# Generated by Django 4.2.10 on 2024-05-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_store_facebook_store_instagram_store_x_red_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='facebook',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='instagram',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='x_red_social',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
