# Generated by Django 4.2.10 on 2024-05-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_store_facebook_alter_store_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='delivery',
        ),
    ]
