# Generated by Django 4.2.10 on 2024-05-22 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0031_remove_store_likes_storelike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='administrator',
        ),
        migrations.AddField(
            model_name='store',
            name='administrators',
            field=models.ManyToManyField(related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
