# Generated by Django 4.2.10 on 2024-05-22 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_remove_store_administrator_store_administrators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='administrators',
            new_name='administrator',
        ),
    ]
