# Generated by Django 4.2.10 on 2024-05-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_userstoreassociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
