# Generated by Django 4.2.10 on 2024-06-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_faq_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='account_pay',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='url_pay',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
