// stores
export const CREATE_STORE_SUCCESS = 'CREATE_STORE_SUCCESS';
export const CREATE_STORE_FAIL = 'CREATE_STORE_FAIL';

export const GET_STORE_SUCCESS = 'GET_STORE_SUCCESS';
export const GET_STORE_FAIL = 'GET_STORE_FAIL';

export const GET_STORE_POLICIES_SUCCESS = 'GET_STORE_POLICIES_SUCCESS';
export const GET_STORE_POLICIES_FAIL = 'GET_STORE_POLICIES_FAIL';

export const SET_LOADING_STORE_POLICIES_SUCCESS = 'SET_LOADING_STORE_POLICIES_SUCCESS';
export const REMOVE_LOADING_GET_STORE_POLICIES_FAIL = 'REMOVE_LOADING_GET_STORE_POLICIES_FAIL';

export const CREATE_STORE_POLICIES_SUCCESS = 'CREATE_STORE_POLICIES_SUCCESS';
export const CREATE_STORE_POLICIES_FAIL = 'CREATE_STORE_POLICIES_FAIL';

export const GET_STORE_FAQ_SUCCESS = 'GET_STORE_FAQ_SUCCESS';
export const GET_STORE_FAQ_FAIL = 'GET_STORE_FAQ_FAIL';

export const SET_LOADING_STORE_FAQS = 'SET_LOADING_STORE_FAQS_SUCCESS';
export const REMOVE_LOADING_GET_STORE_FAQS = 'REMOVE_LOADING_GET_STORE_FAQS_FAIL';

export const GET_STORE_LIKES_DISLIKE_SUCCESS = 'GET_STORE_LIKES_DISLIKE_SUCCESS';
export const GET_STORE_LIKES_DISLIKE_FAIL = 'GET_STORE_LIKES_DISLIKE_FAIL';

// loading
export const SET_LOADED_STORE = 'SET_LOADED_STORE';
export const REMOVE_LOADED_STORE = 'REMOVE_LOADED_STORE';



