// stores
export const CREATE_STORE_SUCCESS = 'CREATE_STORE_SUCCESS';
export const CREATE_STORE_FAIL = 'CREATE_STORE_FAIL';

export const GET_STORE_SUCCESS = 'GET_STORE_SUCCESS';
export const GET_STORE_FAIL = 'GET_STORE_FAIL';


// loading
export const SET_LOADED_STORE = 'SET_LOADED_STORE';
export const REMOVE_LOADED_STORE = 'REMOVE_LOADED_STORE';
