# Generated by Django 5.0 on 2024-02-11 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_store', '0001_initial'),
        ('user_profile', '0009_userprofile_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment_store',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
