# Generated by Django 5.0 on 2024-02-26 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_store', '0004_alter_coment_store_content'),
        ('store', '0018_alter_store_nit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment_store',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_store', to='store.store'),
        ),
        migrations.AlterField(
            model_name='coment_store',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_store', to=settings.AUTH_USER_MODEL),
        ),
    ]
