# Generated by Django 5.0 on 2024-01-18 18:53

import apps.currency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeCurrency', models.CharField(max_length=3)),
            ],
        ),
    ]
