# Generated by Django 5.0 on 2024-01-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_rename_typecurrency_currency_typecurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='typecurrency',
            field=models.CharField(max_length=3),
        ),
    ]
