# Generated by Django 5.0 on 2024-01-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_currency_typecurrency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'currency', 'verbose_name_plural': 'currencies'},
        ),
    ]
