# Generated by Django 4.2.10 on 2024-05-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_currency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='decimal_places',
            field=models.IntegerField(default=2),
        ),
    ]
