# Generated by Django 4.2.10 on 2024-05-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_currency_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='decimal_places',
            field=models.IntegerField(default=3),
        ),
    ]
