export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS';
export const GET_INVOICES_FAIL = 'GET_INVOICES_FAIL';

export const SET_LOADING_INVOICES = 'SET_LOADING_INVOICES';
export const REMOVE_LOADING_INVOICES = 'REMOVE_LOADING_INVOICES';

export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
export const GET_STATUS_FAIL = 'GET_STATUS_FAIL';

export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const REMOVE_LOADING_STATUS = 'REMOVE_LOADING_STATUS';



export const GET_INVOICE_SUCCESS = 'GET_INVOICE_SUCCESS';
export const GET_INVOICE_FAIL = 'GET_INVOICE_FAIL';

export const SET_LOADING_INVOICE = 'SET_LOADING_INVOICE';
export const REMOVE_LOADING_INVOICE = 'REMOVE_LOADING_INVOICE';


