# Generated by Django 5.0 on 2023-12-14 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
    ]
