# Generated by Django 4.2.10 on 2024-03-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
