# Generated by Django 4.2.10 on 2024-05-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_useraccount_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_primary_store_admin',
            field=models.BooleanField(default=False),
        ),
    ]
