# Generated by Django 4.2.10 on 2024-06-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_useraccount_is_primary_store_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_login_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
