# Generated by Django 4.2.10 on 2024-06-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_useraccount_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
