# Generated by Django 4.2.10 on 2024-06-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_useraccount_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_login_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
