# Generated by Django 4.2.10 on 2024-06-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_useraccount_failed_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
