# Generated by Django 4.2.10 on 2024-06-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_useraccount_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
