# Generated by Django 4.2.10 on 2024-06-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_useraccount_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
