# Generated by Django 4.2.10 on 2024-06-08 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_useraccount_lock_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='lock_until',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_login_attempt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
