# Generated by Django 4.2.10 on 2024-06-08 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_remove_useraccount_lock_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='last_login_attempt',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='login_attempts',
        ),
    ]
