# Generated by Django 4.2.10 on 2024-06-08 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_remove_useraccount_last_login_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_login_attempt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
