# Generated by Django 4.2.10 on 2024-06-08 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_useraccount_last_login_attempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='last_login_attempt',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='login_attempts',
        ),
    ]
