# Generated by Django 4.2.10 on 2024-06-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_remove_useraccount_last_login_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
