// cities
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING';
export const REMOVE_PRODUCTS_LOADING = 'REMOVE_PRODUCTS_LOADING';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';


export const REMOVE_PRODUCT_FAIL_LOADING = 'REMOVE_PRODUCT_FAIL_LOADING';
export const SET_PRODUCT_SUCCESS_LOADING = 'SET_PRODUCT_SUCCESS_LOADING';



