// cities
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING';
export const REMOVE_PRODUCTS_LOADING = 'REMOVE_PRODUCTS_LOADING';